return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "html",
      "javascript",
      "json",
      "latex",
      "lua",
      "luap",
      "markdown",
      "markdown_inline",
      "nix",
      "python",
      "query",
      "regex",
      "rust",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
    rainbow = {
      enable = true,
      disable = {},
    },
    highlight = {
      enable = true,
      disable = { "latex" },
    },
  },
  dependencies = { "OXY2DEV/markview.nvim" },
}
